[package]
name = "timer"
version = "0.3.0"
authors = ["Victor Deryagin <vderyagin@gmail.com>"]
edition = "2024"

[dependencies]
ansi_term = "*"
clap = { version = "*", features = ["derive"] }
regex = "*"
rodio = "*"
time = "*"
